<template>
  <el-dialog
    :model-value="visible"
    :title="isEdit ? t('ops.task.edit') : t('ops.task.add')"
    width="680px"
    append-to-body
    @update:model-value="handleClose"
  >
    <el-form
      ref="formRef"
      :model="model"
      :rules="rules"
      label-width="110px"
      :disabled="saving"
    >
      <el-row :gutter="20">
        <el-col :span="12">
          <el-form-item
            :label="t('ops.task.taskName')"
            prop="taskName"
          >
            <el-input
              v-model="model.taskName"
              :placeholder="t('ops.task.form.taskNamePlaceholder')"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item
            :label="t('ops.task.taskGroup')"
            prop="taskGroup"
          >
            <el-select
              v-model="model.taskGroup"
              :placeholder="t('ops.task.form.taskGroupPlaceholder')"
              style="width: 100%"
            >
              <el-option
                label="system"
                value="system"
              />
              <el-option
                label="basic"
                value="basic"
              />
              <el-option
                label="crm"
                value="crm"
              />
              <el-option
                label="mall"
                value="mall"
              />
              <el-option
                label="site"
                value="site"
              />
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>

      <!-- Cron 配置区域 -->
      <el-divider content-position="left">
        {{ t('ops.task.cronConfig') }}
      </el-divider>
      
      <el-row :gutter="20">
        <!-- 执行频率选择 -->
        <el-col :span="12">
          <el-form-item
            :label="t('ops.task.cronPattern')"
            prop="cronPattern"
          >
            <el-select
              v-model="cronBuilder.pattern"
              style="width: 100%"
              @change="onPatternChange"
            >
              <el-option
                v-for="opt in PATTERN_OPTIONS"
                :key="opt.value"
                :label="opt.label"
                :value="opt.value"
              />
            </el-select>
          </el-form-item>
        </el-col>

        <!-- 时间选择（除每小时外都需要） -->
        <el-col
          v-if="cronBuilder.pattern !== 'hourly'"
          :span="12"
        >
          <el-form-item :label="t('ops.task.cronTime')">
            <el-time-picker
              v-model="timeValue"
              format="HH:mm"
              value-format="HH:mm"
              :clearable="false"
              style="width: 100%"
            />
          </el-form-item>
        </el-col>

        <!-- 星期选择（每周） -->
        <el-col
          v-if="cronBuilder.pattern === 'weekly'"
          :span="12"
        >
          <el-form-item :label="t('ops.task.cronDayOfWeek')">
            <el-select
              v-model="cronBuilder.dayOfWeek"
              style="width: 100%"
            >
              <el-option
                v-for="day in DAYS_OF_WEEK"
                :key="day.value"
                :label="day.label"
                :value="day.value"
              />
            </el-select>
          </el-form-item>
        </el-col>

        <!-- 日期选择（每月） -->
        <el-col
          v-if="cronBuilder.pattern === 'monthly'"
          :span="12"
        >
          <el-form-item :label="t('ops.task.cronDayOfMonth')">
            <el-input-number
              v-model="cronBuilder.dayOfMonth"
              :min="1"
              :max="31"
              style="width: 100%"
            />
          </el-form-item>
        </el-col>

        <!-- 自定义 Cron 输入 -->
        <el-col
          v-if="cronBuilder.pattern === 'custom'"
          :span="24"
        >
          <el-form-item
            :label="t('ops.task.cron')"
            prop="cron"
          >
            <el-input
              v-model="model.cron"
              :placeholder="t('ops.task.form.cronPlaceholder')"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <!-- Cron 预览 -->
      <el-row
        v-if="cronBuilder.pattern !== 'custom'"
        :gutter="20"
      >
        <el-col :span="24">
          <el-form-item :label="t('ops.task.cronPreview')">
            <el-alert
              :title="descriptionText"
              type="info"
              :closable="false"
              show-icon
            />
          </el-form-item>
        </el-col>
        <el-col :span="24">
          <el-form-item :label="t('ops.task.cronExpression')">
            <el-input
              v-model="cronBuilder.cronExpression"
              readonly
              class="cron-readonly"
            >
              <template #append>
                <el-tag
                  type="success"
                  size="small"
                >
                  {{ t('ops.task.autoGenerated') }}
                </el-tag>
              </template>
            </el-input>
          </el-form-item>
        </el-col>
      </el-row>

      <el-divider />

      <el-row :gutter="20">
        <el-col :span="24">
          <el-form-item
            :label="t('ops.task.className')"
            prop="className"
          >
            <el-input
              v-model="model.className"
              :placeholder="t('ops.task.form.classNamePlaceholder')"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item
            :label="t('ops.task.methodName')"
            prop="methodName"
          >
            <el-input
              v-model="model.methodName"
              :placeholder="t('ops.task.form.methodNamePlaceholder')"
            />
          </el-form-item>
        </el-col>
        <el-col :span="24">
          <el-form-item
            :label="t('ops.task.description')"
            prop="description"
          >
            <el-input
              v-model="model.description"
              type="textarea"
              :rows="2"
              :placeholder="t('ops.task.form.descriptionPlaceholder')"
            />
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>

    <template #footer>
      <el-button @click="handleClose(false)">
        {{ t('common.cancel') }}
      </el-button>
      <el-button
        type="primary"
        :loading="saving"
        @click="handleSubmit"
      >
        {{ t('common.confirm') }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, reactive, watch, computed } from 'vue'
import type { FormInstance, FormRules } from 'element-plus'
import { ElMessage } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { createTask, updateTask } from '@/api/ops/task'
import type { Task } from '@/types/ops'
import { useCronBuilder } from '@/composables/useCronBuilder'

const props = defineProps<{
  visible: boolean
  isEdit: boolean
  rowData?: Task
}>()

const emit = defineEmits<{
  (e: 'update:visible', value: boolean): void
  (e: 'success'): void
}>()

const { t } = useI18n()

const formRef = ref<FormInstance>()
const saving = ref(false)

const model = reactive({
  taskName: '',
  taskGroup: 'system',
  cron: '',
  className: '',
  methodName: 'Execute',
  description: '',
})

// Cron 构建器
const cronBuilder = useCronBuilder()

// 星期选项（支持 i18n）
const DAYS_OF_WEEK = computed(() => [
  { value: 1, label: t('common.monday') },
  { value: 2, label: t('common.tuesday') },
  { value: 3, label: t('common.wednesday') },
  { value: 4, label: t('common.thursday') },
  { value: 5, label: t('common.friday') },
  { value: 6, label: t('common.saturday') },
  { value: 7, label: t('common.sunday') },
])

// 频率选项（支持 i18n）
const PATTERN_OPTIONS = computed(() => [
  { value: 'hourly' as const, label: t('ops.task.patternHourly'), desc: t('ops.task.patternHourlyDesc') },
  { value: 'daily' as const, label: t('ops.task.patternDaily'), desc: t('ops.task.patternDailyDesc') },
  { value: 'weekly' as const, label: t('ops.task.patternWeekly'), desc: t('ops.task.patternWeeklyDesc') },
  { value: 'monthly' as const, label: t('ops.task.patternMonthly'), desc: t('ops.task.patternMonthlyDesc') },
  { value: 'custom' as const, label: t('ops.task.patternCustom'), desc: t('ops.task.patternCustomDesc') },
])

// 时间选择器值（双向绑定到 hour/minute）
const timeValue = computed({
  get: () => {
    const h = String(cronBuilder.hour).padStart(2, '0')
    const m = String(cronBuilder.minute).padStart(2, '0')
    return `${h}:${m}`
  },
  set: (val: string) => {
    if (val) {
      const [h, m] = val.split(':').map(Number)
      cronBuilder.hour = h
      cronBuilder.minute = m
    }
  }
})

// 生成可读的描述
const descriptionText = computed(() => {
  const timeStr = `${String(cronBuilder.hour).padStart(2, '0')}:${String(cronBuilder.minute).padStart(2, '0')}`
  
  switch (cronBuilder.pattern) {
    case 'hourly':
      return t('ops.task.descHourly')
    case 'daily':
      return t('ops.task.descDaily', { time: timeStr })
    case 'weekly':
      const dayName = DAYS_OF_WEEK.value.find(d => d.value === cronBuilder.dayOfWeek)?.label || ''
      return t('ops.task.descWeekly', { day: dayName, time: timeStr })
    case 'monthly':
      return t('ops.task.descMonthly', { day: String(cronBuilder.dayOfMonth), time: timeStr })
    default:
      return t('ops.task.descCustom')
  }
})

const rules: FormRules = {
  taskName: [{ required: true, message: () => t('common.required'), trigger: 'blur' }],
  cron: [{ required: true, message: () => t('common.required'), trigger: 'blur' }],
  className: [{ required: true, message: () => t('common.required'), trigger: 'blur' }],
}

// 当模式改变时，如果是自定义模式需要清空自动生成的 cron
const onPatternChange = (pattern: string) => {
  if (pattern === 'custom') {
    // 保持当前 cron 值让用户编辑
  } else {
    // 自动更新 model.cron
    model.cron = cronBuilder.cronExpression
  }
}

// 监听 cron 构建器生成的表达式变化（非自定义模式）
watch(() => cronBuilder.cronExpression, (newCron) => {
  if (cronBuilder.pattern !== 'custom') {
    model.cron = newCron
  }
}, { immediate: true })

watch(() => props.visible, (val) => {
  if (!val) return
  if (props.isEdit && props.rowData) {
    model.taskName = props.rowData.taskName
    model.taskGroup = props.rowData.taskGroup
    model.cron = props.rowData.cron
    model.className = props.rowData.className
    model.methodName = props.rowData.methodName
    model.description = props.rowData.description
    
    // 解析现有 cron 表达式
    cronBuilder.parseCron(props.rowData.cron)
  } else {
    model.taskName = ''
    model.taskGroup = 'system'
    model.cron = ''
    model.className = ''
    model.methodName = 'Execute'
    model.description = ''
    cronBuilder.reset()
  }
  formRef.value?.clearValidate()
})

const handleClose = (val: boolean = false) => {
  emit('update:visible', val)
}

const handleSubmit = async () => {
  if (!formRef.value) return
  await formRef.value.validate(async (valid) => {
    if (!valid) return
    saving.value = true
    try {
      if (props.isEdit && props.rowData) {
        await updateTask(props.rowData.id, model)
        ElMessage.success(t('common.success'))
      } else {
        await createTask(model)
        ElMessage.success(t('common.success'))
      }
      emit('success')
      handleClose(false)
    } finally {
      saving.value = false
    }
  })
}
</script>

<style scoped>
.cron-readonly :deep(.el-input__wrapper) {
  background-color: var(--el-fill-color-light);
}
</style>
